create table if not exists public.samples (
    id bigint generated by default as identity primary key,

    indent_no text not null,
    order_date date not null,
    buyer text not null,
    article text not null,
    color text not null,

    thickness_mm numeric(10,2),
    avg_area_sdm numeric(12,2),
    quantity integer not null default 1,

    remarks text,
    supplier text not null,

    delivered_date date,
    status text not null default 'WIP',

    unique_id text not null unique,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint samples_status_check
        check (status in ('WIP', 'Completed')),

    constraint samples_quantity_check
        check (quantity > 0),

    constraint samples_thickness_check
        check (thickness_mm is null or thickness_mm >= 0),

    constraint samples_avg_area_check
        check (avg_area_sdm is null or avg_area_sdm >= 0),

    constraint samples_completed_date_check
        check (
            status = 'WIP'
            or delivered_date is not null
        )
);

create index if not exists samples_status_idx
    on public.samples(status);

create index if not exists samples_buyer_idx
    on public.samples(buyer);

create index if not exists samples_supplier_idx
    on public.samples(supplier);

create index if not exists samples_article_idx
    on public.samples(article);

create index if not exists samples_order_date_idx
    on public.samples(order_date desc);


-- Optional automatic updated_at trigger.
create or replace function public.set_samples_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists samples_updated_at on public.samples;

create trigger samples_updated_at
before update on public.samples
for each row
execute function public.set_samples_updated_at();


-- ------------------------------------------------------------------
-- Row Level Security
-- ------------------------------------------------------------------
-- This setup is convenient for a private/internal Streamlit app.
-- If you later add Supabase Auth, replace these policies with
-- authenticated-user policies.

alter table public.samples enable row level security;

drop policy if exists "samples_select" on public.samples;
drop policy if exists "samples_insert" on public.samples;
drop policy if exists "samples_update" on public.samples;
drop policy if exists "samples_delete" on public.samples;

create policy "samples_select"
on public.samples
for select
to anon, authenticated
using (true);

create policy "samples_insert"
on public.samples
for insert
to anon, authenticated
with check (true);

create policy "samples_update"
on public.samples
for update
to anon, authenticated
using (true)
with check (true);

create policy "samples_delete"
on public.samples
for delete
to anon, authenticated
using (true);
